import type { L } from './types';

export interface CvEntry {
  /** Left margin: dates, set in mono. */
  when: L;
  title: L;
  org?: L;
  place?: L;
  /** Bullet points. Keep to two or three; a CV is not a diary. */
  points: L<string[]>;
}

export interface CvSection {
  id: string;
  heading: L;
  entries: CvEntry[];
}

/**
 * The CV's version stamp. It is what the download link appends to invalidate
 * caches, so it has to change whenever the PDF does. A date cannot: the CV was
 * rebuilt twice on one day and the second rebuild kept the first one's URL, so
 * the CDN answered that URL with the older file. It carries a time for that
 * reason, as the job résumé's does (see RESUME_UPDATED below), and the reader
 * sees only the date.
 */
export const CV_UPDATED = '2026-10-11T03:30';

/** The stamp's date part, which is what gets shown. */
export const CV_UPDATED_ON = CV_UPDATED.split('T')[0];

/**
 * Version stamp for the Chinese job résumé (public/resume-zh.pdf).
 *
 * That PDF is a different document, built by scripts/build-resume-zh.mjs from
 * scripts/resume-zh-data.mjs, and it is rebuilt on its own schedule. It used to
 * borrow CV_UPDATED for its download link, so a rebuilt résumé kept advertising
 * the CV's date and returning readers were served a cached copy. The test in
 * tests/content.test.ts pins this to the UPDATED constant the build script
 * carries, so the two cannot drift apart again.
 *
 * That constant is a timestamp rather than a date: the link's whole job is to
 * change when the file changes, and a date cannot distinguish two rebuilds in
 * one day. The résumé prints only its date part.
 */
export const RESUME_UPDATED = '2026-10-11T02:45';

/**
 * This is the academic CV, written for graduate admissions in learning
 * engineering, educational technology and HCI. It is deliberately not a
 * job résumé: media production, marketing metrics and student-society
 * office-holding are omitted because they do not bear on research potential.
 * Those live on /about instead, and in the separate Chinese job résumé
 * generated by scripts/build-resume-zh.mjs.
 *
 * One page is the target. Adding an entry means removing one.
 */

export const EDUCATION: CvSection = {
  id: 'education',
  heading: { en: 'Education', zh: '教育背景' },
  entries: [
    {
      when: { en: 'Sep 2023 to Jun 2027 (expected)', zh: '2023.09 – 2027.06（预计）' },
      title: {
        en: 'Dual bachelor’s degree: Translation Studies and Computer Science',
        zh: '翻译学 + 计算机科学 双学士学位（本科）',
      },
      org: {
        en: 'Guangdong University of Foreign Studies · Macao Polytechnic University',
        zh: '广东外语外贸大学 · 澳门理工大学',
      },
      place: {
        en: 'Guangzhou and Macao',
        zh: '广州 / 澳门',
      },
      points: {
        en: [
          'Translation (GDUFS): EN–ZH contrastive translation, foundations of translation, English translation of Chinese culture, translation and international communication, interpreting, CAT. In progress: translation data mining.',
          'Computer science (MPU): data structures and algorithms, Python and Java, computer organisation, databases, discrete mathematics, networks, software engineering, web development, AI, data science. In progress: NLP, machine translation, computer security.',
        ],
        zh: [
          '广外翻译方向：英汉对比翻译、基础笔译、中国文化英译、翻译与国际传播、交替传译、同声传译、计算机辅助翻译、语言学导论；在读课程为翻译数据挖掘与应用。',
          '澳门理工计算机方向：数据结构与算法、Python / Java 程序设计、计算机组成原理、数据库设计、离散数学、电脑网络、软件工程、网页设计与开发、人工智能、数据科学与商业分析；在读课程为自然语言处理、机器翻译、电脑安全（Computer Security）。',
        ],
      },
    },
  ],
};

export const RESEARCH: CvSection = {
  id: 'research',
  heading: { en: 'Research', zh: '研究经历' },
  entries: [
    {
      when: { en: 'May 2026 to present', zh: '2026.05 至今' },
      title: {
        en: 'PaperCraft: a teacher-in-the-loop LLM authoring tool for Cambridge KET/PET',
        zh: 'PaperCraft：剑桥 KET / PET 教师在环智能出题系统',
      },
      org: {
        en: 'Final year project · sole developer and research design',
        zh: '毕业设计 · 独立开发与研究设计',
      },
      points: {
        en: [
          'Designed the authoring harness the model runs inside: a fixed call sequence, machine-checked output and typed repair of a named failure.',
          'Added a self-improving loop: an offline pass reads the teacher’s correction log, induces candidate rules and folds accepted ones into later drafts, isolated per teacher across 15 item types.',
          'Evaluated the output two ways: structural gates on every draft, an independent audit on every rule.',
        ],
        zh: [
          '模型运行于专为出题场景定制的 harness，调用顺序固定，输出经机器校验，失败按类型修复。',
          '离线读取教师批改记录并归纳候选规则，经教师采纳后进入后续出题；规则按教师隔离，覆盖 15 种剑桥题型。',
          '每份初稿均经结构校验，每条候选规则均经独立审计。',
        ],
      },
    },
    {
      when: { en: 'Jul 2026', zh: '2026.07' },
      title: {
        en: 'IELTS Coach: an open-source agent that interviews the learner before it writes',
        zh: 'IELTS Coach：雅思口语与写作备考 Agent Skill',
      },
      org: {
        en: 'Open-source learning tool (MIT) · sole developer',
        zh: '开源项目（MIT 许可）· 独立开发',
      },
      points: {
        en: [
          'Released an open-source agent (MIT) that collects the learner’s own material through a structured multi-step form, then generates answers constrained to the four IELTS band criteria. Covers 100 topics in the 2026 Sep–Dec bank.',
          'Persisted per-topic state in JSON so study plans carry across sessions and exam seasons; built a validated bank parser, a one-click summary-site generator and an MCP vision proxy that lets text-only models handle Writing Task 1.',
        ],
        zh: [
          '以结构化多步表单采集学习者自身素材，再按雅思四项评分标准生成范文；题库覆盖 2026 年 9–12 月季度的 100 个话题。',
          '以 JSON 按话题保存学习状态，学习计划可跨会话、跨考试季度延续；实现带校验的题库解析、一键生成备考总结站点，以及供纯文本模型处理写作 Task 1 图表的 MCP 视觉服务。',
        ],
      },
    },
    {
      when: { en: 'Oct 2025 to present', zh: '2025.10 至今' },
      title: {
        en: 'Transcreation in the age of generative AI: human translators versus LLMs in film title translation',
        zh: '生成式 AI 时代的译创研究：电影片名翻译中的人工译者与大语言模型对比',
      },
      org: {
        en: 'Co-authored paper in preparation · three-person faculty-advised team',
        zh: '合著论文（撰写中）· 三人课题组，导师指导',
      },
      points: {
        en: [
          'Developed a three-tier cognitive-linguistic framework separating translation strategy, cognitive operation and cultural schema, ranking four schema operations by cognitive load.',
          'Reviewed work on functionalist title translation, regional norms across Greater China and cultural bias in frontier models; argued that overlap metrics such as BLEU penalise the divergence that professional judgement produces.',
        ],
        zh: [
          '构建三层认知语言学框架，区分翻译策略、认知操作与文化图式，并依认知负荷为四类图式操作分级。',
          '梳理功能主义片名翻译、两岸三地的译名规范差异及前沿模型的文化偏见等研究；论证 BLEU 等参考重叠类指标不适用于译创评估，因其惩罚的恰是体现专业判断的偏离。',
        ],
      },
    },
  ],
};

export const TEACHING: CvSection = {
  id: 'teaching',
  heading: { en: 'Teaching', zh: '教学经历' },
  entries: [
    {
      when: { en: 'May 2024 to Sep 2025', zh: '2024.05 – 2025.09' },
      title: { en: 'Primary English Teacher, Cambridge KET', zh: '小学英语教师（兼职）' },
      org: { en: 'Guangzhou Bella Education Technology', zh: '广州贝拉教育科技有限公司' },
      place: { en: 'Guangzhou', zh: '广州' },
      points: {
        en: [
          'Taught two Cambridge KET classes and New Concept English; authored all lesson plans, courseware and weekly practice sets.',
          'Tracked mastery of KET item types through classwork and periodic assessments; adjusted instructional pacing accordingly.',
        ],
        zh: [
          '主讲两个剑桥 KET 班及《新概念英语》课程，独立完成教案、课件与每周练习的编写。',
          '通过课堂练习与阶段测评跟踪学生对 KET 各题型的掌握情况，并据此调整教学进度。',
        ],
      },
    },
    {
      when: { en: 'Jan 2024 to Feb 2024', zh: '2024.01 – 2024.02' },
      title: {
        en: 'English Teaching Assistant, Middle School Division',
        zh: '中学部英语助教',
      },
      org: {
        en: 'New Oriental Education & Technology Group',
        zh: '新东方教育科技集团',
      },
      place: { en: 'Foshan', zh: '佛山' },
      points: {
        en: [
          'Supported middle-school English instruction; maintained a quantitative record of interaction frequency and topic-level mastery; delivered differentiated one-to-one tutoring with error-attribution analysis for parents.',
        ],
        zh: [
          '协助主讲教师开展中学英语教学；建立学生互动频次与知识点掌握情况的量化记录，据此分层开展一对一辅导，并定期向家长反馈错题归因。',
        ],
      },
    },
  ],
};

export const EXPERIENCE: CvSection = {
  id: 'experience',
  heading: { en: 'Technical experience', zh: '实习经历' },
  entries: [
    {
      when: { en: 'Jun 2026 to Aug 2026', zh: '2026.06 – 2026.08' },
      title: { en: 'IT Department Intern', zh: 'IT 部实习生' },
      org: {
        en: 'Guangdong Dowstone Technology Co., Ltd. (SZSE: 300409)',
        zh: '广东道氏技术股份有限公司（深交所 300409）',
      },
      place: { en: 'Foshan', zh: '佛山' },
      points: {
        en: [
          'Deployed and tested quantised open-source LLMs on premises via Ollama; benchmarked inference throughput across configurations to inform model selection.',
          'Helped build a retrieval-augmented generation knowledge base over internal business documents, covering preprocessing and ingestion; supported ERP and WMS maintenance and testing.',
        ],
        zh: [
          '使用 Ollama 在企业内网部署并测试量化开源大模型，对比不同配置下的推理吞吐，为模型选型提供依据。',
          '参与搭建基于本地模型的企业知识库，负责业务文档的预处理与接入；协助 ERP、WMS 系统的日常维护与测试。',
        ],
      },
    },
  ],
};

export const AWARDS: CvSection = {
  id: 'awards',
  heading: { en: 'Awards & certifications', zh: '获奖与证书' },
  entries: [
    {
      when: { en: '2025', zh: '2025' },
      title: {
        en: 'First Place, CIUTI Short Video Contest, on the power of human translation and interpreting in the age of AI',
        zh: 'CIUTI（国际大学翻译学院联合会）短视频大赛一等奖（主题：人工智能时代人类翻译的力量）',
      },
      points: { en: [], zh: [] },
    },
    {
      when: { en: '2023', zh: '2023' },
      title: {
        en: 'Outstanding Volunteer, 5th World Media Summit, reception for the BBC and NHK delegations',
        zh: '第五届世界媒体峰会优秀志愿者（负责 BBC、NHK 等媒体代表团接待）',
      },
      points: { en: [], zh: [] },
    },
    {
      when: { en: 'Certification', zh: '证书' },
      title: {
        en: 'NCRE Level 3, Linux application and development',
        zh: '全国计算机等级考试三级（Linux 应用与开发技术）',
      },
      points: { en: [], zh: [] },
    },
  ],
};

/**
 * Writing, media and outreach. Deliberately NOT part of CV_SECTIONS: an
 * admissions committee reading a one-page academic CV does not need view counts
 * or a student-society title. It is rendered on /about instead, where the
 * breadth is the point rather than a distraction.
 */
export const WRITING_MEDIA: CvSection = {
  id: 'communication',
  heading: { en: 'Writing & communication', zh: '写作与传播' },
  entries: [
    {
      when: { en: 'Apr 2025 to May 2025', zh: '2025.04 – 2025.05' },
      title: {
        en: 'Overseas Buyer Vlog Team, External Liaison Department',
        zh: '对外联络部 境外采购商 Vlog 工作组',
      },
      org: {
        en: 'China Foreign Trade Centre (Canton Fair)',
        zh: '中国对外贸易中心集团有限公司（广交会）',
      },
      place: { en: 'Guangzhou', zh: '广州' },
      points: {
        en: [
          'Led a three-person team and set up a standard workflow from planning to on-site execution, interviewing overseas buyers at the fair and delivering more than 20 promotional videos.',
          'One video passed 100,000 views on the Canton Fair’s official overseas accounts. Also helped run the awards ceremony and two cultural-experience activities.',
        ],
        zh: [
          '带领三人小组建立从策划到现场执行的标准化流程，在展会期间采访境外采购商，交付 20 余条宣传视频。',
          '其中一条在广交会官方海外账号播放量超过十万；另协助筹办颁奖典礼及两项传统文化体验活动。',
        ],
      },
    },
    {
      when: { en: 'Ongoing', zh: '持续进行' },
      title: { en: 'Contracted author, sspai Matrix', zh: '少数派 Matrix 签约作者' },
      points: {
        en: [
          'Long-form technology and digital-practice essays on a leading Chinese technology platform; four pieces, more than 181,000 cumulative reads.',
        ],
        zh: ['在国内主流科技媒体少数派发表技术与数字生活类长文四篇，累计阅读 18.1 万+。'],
      },
    },
    {
      when: { en: 'Ongoing', zh: '持续进行' },
      title: {
        en: 'Author, “English, Seriously” (WeChat)',
        zh: '公众号「一本正经说英语」主理人',
      },
      points: {
        en: ['Essays on English etymology and historical linguistics for a subscriber audience.'],
        zh: ['面向订阅读者撰写英语词源与历史语言学文章。'],
      },
    },
    {
      when: { en: 'Oct 2023 to present', zh: '2023.10 至今' },
      title: {
        en: 'Head of News & Communication, Student Alumni Association',
        zh: '学生校友工作联合会新闻传播部部长',
      },
      org: { en: 'GDUFS Alumni Affairs Office', zh: '广东外语外贸大学校友发展与合作事务处' },
      points: {
        en: [
          'Wrote and published widely read features; interviewed community figures including the president of the United Chinese Association of Southern California; ran homecoming reception.',
        ],
        zh: [
          '撰写并发布多篇高阅读量报道，采访美国南加州华人联合总会会长等人士；负责校友返校接待工作。',
        ],
      },
    },
  ],
};

export const SKILLS = {
  heading: { en: 'Skills', zh: '技能' } as L,
  groups: [
    {
      label: { en: 'Languages', zh: '语言' } as L,
      items: {
        en: [
          'Cantonese (native)',
          'Mandarin Chinese (native)',
          'English (fluent)',
          'Japanese (intermediate)',
        ],
        zh: [
          '粤语（母语）',
          '普通话（母语）',
          '英语（熟练，IELTS 7.5）',
          '日语（JLPT N4）',
        ],
      } as L<string[]>,
    },
    {
      label: { en: 'Building', zh: '开发' } as L,
      items: {
        en: [
          'TypeScript',
          'React / Next.js',
          'Python',
          'Java',
          'PostgreSQL / Supabase',
          'LLM pipelines, RAG and agents',
        ],
        zh: [
          'TypeScript',
          'React / Next.js',
          'Python',
          'Java',
          'PostgreSQL / Supabase',
          '大模型应用开发（RAG、Agent）',
        ],
      } as L<string[]>,
    },
    {
      label: { en: 'Measurement', zh: '测量与分析' } as L,
      items: {
        en: [
          'Classical item analysis',
          'SUS, NASA-TLX and rubric design',
          'SQL',
          'R',
        ],
        zh: ['经典测量理论项目分析', 'SUS、NASA-TLX 量表与评分量规设计', 'SQL', 'R'],
      } as L<string[]>,
    },
  ],
};

export const CV_SECTIONS: CvSection[] = [EDUCATION, RESEARCH, TEACHING, EXPERIENCE, AWARDS];
