import type { L } from './types';

export interface CvEntry {
  /** Left margin: dates, set in mono. */
  when: L;
  title: L;
  org?: L;
  place?: L;
  /** Bullet points. Keep to two or three; a CV is not a diary. */
  points: L<string[]>;
}

export interface CvSection {
  id: string;
  heading: L;
  entries: CvEntry[];
}

export const CV_UPDATED = '2026-08-03';

/**
 * This is the academic CV, written for graduate admissions in learning
 * engineering, educational technology and HCI. It is deliberately not a
 * job résumé: media production, marketing metrics and student-society
 * office-holding are omitted because they do not bear on research potential.
 * Those live on /about instead, and in the separate Chinese job résumé
 * generated by scripts/build-resume-zh.mjs.
 *
 * One page is the target. Adding an entry means removing one.
 */

export const EDUCATION: CvSection = {
  id: 'education',
  heading: { en: 'Education', zh: '教育背景' },
  entries: [
    {
      when: { en: 'Sep 2023 to Jun 2027 (expected)', zh: '2023.09 至 2027.06（预计）' },
      title: {
        en: 'Dual bachelor’s degree: Translation Studies and Computer Science',
        zh: '翻译学与计算机科学双学士学位',
      },
      org: {
        en: 'Guangdong University of Foreign Studies · Macao Polytechnic University',
        zh: '广东外语外贸大学 · 澳门理工大学',
      },
      place: {
        en: 'Guangzhou and Macao',
        zh: '广州 / 澳门',
      },
      points: {
        en: [
          'Translation at GDUFS: contrastive EN–ZH translation, consecutive and simultaneous interpreting, computer-aided translation.',
          'Computer science at MPU: data structures and algorithms, database design, discrete mathematics, artificial intelligence, data science and business analytics. In progress: natural language processing, machine translation.',
        ],
        zh: [
          '广外翻译方向：英汉对比翻译、交替传译、同声传译、计算机辅助翻译、语言学导论。',
          '澳门理工计算机方向：数据结构与算法、数据库设计、离散数学、人工智能、数据科学与商业分析。在读课程为自然语言处理与机器翻译。',
        ],
      },
    },
  ],
};

export const RESEARCH: CvSection = {
  id: 'research',
  heading: { en: 'Research', zh: '研究经历' },
  entries: [
    {
      when: { en: 'May 2026 to present', zh: '2026.05 至今' },
      title: {
        en: 'PaperCraft: a teacher-in-the-loop LLM authoring tool for Cambridge KET/PET',
        zh: 'PaperCraft：面向剑桥 KET / PET 的教师在环出题工具',
      },
      org: {
        en: 'Final year project · sole developer and research design',
        zh: '毕业设计 · 独立开发与研究设计',
      },
      points: {
        en: [
          'Designed a seven-stage generation pipeline in which teacher adjudication is a required gate, encoded published item-writing rules for 15 Cambridge item types, and audited generated text against CEFR A2/B1 wordlists.',
          'Instrumented the workflow so that teacher edit distance and classical item statistics (difficulty, point-biserial discrimination, distractor analysis) are captured as a by-product of ordinary use.',
          'Specified the evaluation protocol: within-subject task timing against each teacher’s own manual workflow, SUS, NASA-TLX, a content-quality rubric and interviews. Instruments are complete; data collection has not begun.',
        ],
        zh: [
          '设计七阶段生成管线，把教师裁决设为不可跳过的闸门；为 15 种剑桥题型写入已公开的命题规则，并按 CEFR A2 / B1 词表审计生成文本。',
          '给工作流加了埋点，教师的编辑距离和经典项目统计量（难度、点二列区分度、干扰项分析）在日常使用中自动产生，不额外增加教师负担。',
          '写完整套评估方案：以每位教师自己的手工流程作基线做被试内任务计时，配 SUS、NASA-TLX、内容质量量表和半结构化访谈。量表与流程已就绪，数据收集还没开始。',
        ],
      },
    },
    {
      when: { en: 'Oct 2025 to present', zh: '2025.10 至今' },
      title: {
        en: 'Transcreation in the age of generative AI: human translators versus LLMs in film title translation',
        zh: '生成式 AI 时代的译创：电影片名翻译中人工译者与大语言模型的对比',
      },
      org: {
        en: 'Co-authored paper in preparation · three-person faculty-advised team',
        zh: '合著论文（写作中）· 三人小组，导师指导',
      },
      points: {
        en: [
          'Developed the cognitive-linguistic framework: a three-tier model separating translation strategy from cognitive operation from cultural schema, with four schema operations ranked by cognitive load.',
          'Synthesised the literature on functionalist title translation, regional norm divergence across Greater China and cultural bias in frontier models, verifying every DOI against Crossref. Argued that reference-overlap metrics such as BLEU are structurally unsuited to transcreation, because they penalise precisely the divergence that constitutes professional judgement.',
        ],
        zh: [
          '提出认知语言学层面的分析框架：三层模型把翻译策略、认知运作和文化图式分开来看，并按认知负荷给四种图式操作排序。',
          '完成文献综述，覆盖功能主义片名翻译、大中华区内部的规范差异，以及前沿模型已被记录的文化偏见，全部 DOI 逐条核对 Crossref。并论证 BLEU 这类看重叠度的指标从根上不适合评译创，因为它们扣的分恰恰是专业判断的体现。',
        ],
      },
    },
  ],
};

export const TEACHING: CvSection = {
  id: 'teaching',
  heading: { en: 'Teaching', zh: '教学经历' },
  entries: [
    {
      when: { en: 'May 2024 to Sep 2025', zh: '2024.05 至 2025.09' },
      title: { en: 'Primary English Teacher, Cambridge KET', zh: '小学英语教师（剑桥 KET）' },
      org: { en: 'Guangzhou Bella Education Technology', zh: '广州贝拉教育科技有限公司' },
      place: { en: 'Guangzhou', zh: '广州' },
      points: {
        en: [
          'Taught two small Cambridge KET classes and New Concept English, writing all lesson plans, courseware and weekly practice sets by hand, about two hours a set.',
          'Tracked mastery of KET item types through classwork and periodic tests, adjusting pacing accordingly. That authoring burden, and the inability to control item difficulty from a small pool of past papers, is the problem PaperCraft was built to study.',
        ],
        zh: [
          '带两个剑桥 KET 小班，同时教新概念英语，教案、课件和每周一套练习都是自己手写，一套大约两小时。',
          '通过课堂练习和阶段性测试追踪学生对 KET 考点的掌握情况，据此调整进度。出题负担加上官方真题有限、难度压不住，后来就有了 PaperCraft。',
        ],
      },
    },
    {
      when: { en: 'Jan 2024 to Feb 2024', zh: '2024.01 至 2024.02' },
      title: {
        en: 'English Teaching Assistant, Middle School Division',
        zh: '英语助教（中学部）',
      },
      org: {
        en: 'New Oriental Education & Technology Group',
        zh: '新东方教育科技集团',
      },
      place: { en: 'Foshan', zh: '佛山' },
      points: {
        en: [
          'Supported middle-school English instruction and courseware production, kept a quantitative record of interaction frequency and mastery by topic, and ran differentiated one-to-one support with error-attribution analysis reported to parents.',
        ],
        zh: [
          '配合主讲教师开展中学英语教学，协助制作课件，建立量化记录追踪学生的互动频次与知识点掌握度，并做分层一对一辅导，把错题归因分析反馈给家长。',
        ],
      },
    },
  ],
};

export const EXPERIENCE: CvSection = {
  id: 'experience',
  heading: { en: 'Technical experience', zh: '技术实习经历' },
  entries: [
    {
      when: { en: 'Jun 2026 to Aug 2026', zh: '2026.06 至 2026.08' },
      title: { en: 'IT Department Intern', zh: 'IT 部实习生' },
      org: {
        en: 'Guangdong Dowstone Technology Co., Ltd. (SZSE: 300409)',
        zh: '广东道氏技术股份有限公司（深交所 300409）',
      },
      place: { en: 'Foshan', zh: '佛山' },
      points: {
        en: [
          'Deployed and tested quantised open-source LLMs on premises with Ollama, measuring inference throughput.',
          'Helped build a retrieval-augmented generation knowledge base over internal business documents, covering preprocessing and ingestion; also supported ERP and WMS maintenance and testing.',
        ],
        zh: [
          '用 Ollama 与量化技术在企业内网部署并测试开源大模型，比较不同配置下的推理吞吐。',
          '参与搭建基于本地模型的企业知识库（RAG），负责业务文档的预处理与接入，同时协助 ERP 与 WMS 的维护测试。',
        ],
      },
    },
  ],
};

export const AWARDS: CvSection = {
  id: 'awards',
  heading: { en: 'Awards & certifications', zh: '获奖与证书' },
  entries: [
    {
      when: { en: '2025', zh: '2025' },
      title: {
        en: 'First Place, CIUTI Short Video Contest, on the power of human translation and interpreting in the age of AI',
        zh: 'CIUTI（国际大学翻译学院联合会）短视频大赛一等奖，主题为人工智能时代人类翻译的力量',
      },
      points: { en: [], zh: [] },
    },
    {
      when: { en: '2023', zh: '2023' },
      title: {
        en: 'Outstanding Volunteer, 5th World Media Summit, reception for the BBC and NHK delegations',
        zh: '第五届世界媒体峰会优秀志愿者，负责 BBC、NHK 等媒体代表团接待',
      },
      points: { en: [], zh: [] },
    },
    {
      when: { en: 'Certification', zh: '证书' },
      title: {
        en: 'NCRE Level 3, Linux application and development',
        zh: '全国计算机等级考试三级（Linux 应用与开发技术）',
      },
      points: { en: [], zh: [] },
    },
  ],
};

/**
 * Writing, media and outreach. Deliberately NOT part of CV_SECTIONS: an
 * admissions committee reading a one-page academic CV does not need view counts
 * or a student-society title. It is rendered on /about instead, where the
 * breadth is the point rather than a distraction.
 */
export const WRITING_MEDIA: CvSection = {
  id: 'communication',
  heading: { en: 'Teaching & communication', zh: '教学与传播' },
  entries: [
    {
      when: { en: 'Apr 2025 to May 2025', zh: '2025.04 至 2025.05' },
      title: {
        en: 'Overseas Buyer Vlog Team, External Liaison Department',
        zh: '境外采购商 Vlog 工作组，对外联络部',
      },
      org: {
        en: 'China Foreign Trade Centre (Canton Fair)',
        zh: '中国对外贸易中心集团有限公司（广交会）',
      },
      place: { en: 'Guangzhou', zh: '广州' },
      points: {
        en: [
          'Led a three-person team and set up a standard workflow from planning to on-site execution, interviewing overseas buyers at the fair and delivering more than 20 promotional videos.',
          'One video passed 100,000 views on the Canton Fair’s official overseas accounts. Also helped run the awards ceremony and two cultural-experience activities.',
        ],
        zh: [
          '带三人小组，搭起一套从策划到现场执行的标准流程，在展会上采访境外采购商，交付 20 多条宣传视频。',
          '其中一条在广交会官方境外账号上播放量过十万。另外协助筹办颁奖典礼和两项传统文化体验活动。',
        ],
      },
    },
    {
      when: { en: 'Ongoing', zh: '持续进行' },
      title: { en: 'Contracted author, sspai Matrix', zh: '少数派 Matrix 签约作者' },
      points: {
        en: [
          'Long-form technology and digital-practice essays on a leading Chinese technology platform; four pieces, around 179,000 cumulative reads.',
        ],
        zh: ['为国内主要科技媒体写技术与数字生活类长文，四篇累计阅读约 17.9 万。'],
      },
    },
    {
      when: { en: 'Ongoing', zh: '持续进行' },
      title: {
        en: 'Author, “English, Seriously” (WeChat)',
        zh: '公众号「一本正经说英语」主理人',
      },
      points: {
        en: ['Essays on English etymology and historical linguistics for a subscriber audience.'],
        zh: ['给订阅读者写英语词源和历史语言学的文章。'],
      },
    },
    {
      when: { en: 'Oct 2023 to present', zh: '2023.10 至今' },
      title: {
        en: 'Head of News & Communication, Student Alumni Association',
        zh: '学生校友工作联合会新闻传播部部长',
      },
      org: { en: 'GDUFS Alumni Affairs Office', zh: '广东外语外贸大学校友发展与合作事务处' },
      points: {
        en: [
          'Wrote and published widely read features; interviewed community figures including the president of the United Chinese Association of Southern California; ran homecoming reception.',
        ],
        zh: [
          '撰写并发布多篇高阅读量报道，采访过美国南加州华人联合总会会长等社会人士，并负责校友返校接待。',
        ],
      },
    },
  ],
};

export const SKILLS = {
  heading: { en: 'Skills', zh: '技能' } as L,
  groups: [
    {
      label: { en: 'Languages', zh: '语言' } as L,
      items: {
        en: [
          'Cantonese (native)',
          'Mandarin (PSC Level 2-A)',
          'English (TEM-4, working language)',
          'Japanese (JLPT N4)',
        ],
        zh: [
          '粤语（母语）',
          '普通话（二级甲等）',
          '英语（专业四级，可作工作语言）',
          '日语（JLPT N4）',
        ],
      } as L<string[]>,
    },
    {
      label: { en: 'Building', zh: '开发' } as L,
      items: {
        en: [
          'TypeScript',
          'React / Next.js',
          'Python',
          'Java',
          'PostgreSQL / Supabase',
          'LLM pipelines, RAG and agents',
        ],
        zh: [
          'TypeScript',
          'React / Next.js',
          'Python',
          'Java',
          'PostgreSQL / Supabase',
          '大模型管线、RAG 与 agent',
        ],
      } as L<string[]>,
    },
    {
      label: { en: 'Measurement', zh: '测量与分析' } as L,
      items: {
        en: [
          'Classical item analysis',
          'SUS, NASA-TLX and rubric design',
          'SQL',
          'R',
        ],
        zh: ['经典项目分析', 'SUS、NASA-TLX 与量表设计', 'SQL', 'R'],
      } as L<string[]>,
    },
  ],
};

export const CV_SECTIONS: CvSection[] = [EDUCATION, RESEARCH, TEACHING, EXPERIENCE, AWARDS];
